### ISSUE TITLE
Is there an indicator of the number of slides?

### ISSUE THREAD

**Issue by ixodid198** [juba/shinyglide#19]
In Glide.js there are translucent dots that indicate the number of slides and where you are in the order. 
![Screen Shot 2020-12-19 at 8 43 27 PM](https://user-images.githubusercontent.com/12522241/102703294-0b003a00-423b-11eb-88a3-3106a217564c.png)
Does shinyglide have a similar indicator? If so, how do I turn it on?

Simple Example Without Indicator
```
library(shiny)
library(shinyglide)

ui <- fluidPage(
  titlePanel("Basic shinyglide app"),
  glide(
    next_label = paste("Next", icon("play", lib = "glyphicon")),
    previous_label = span(style = "opacity: 0.5;", "Previous"),
    
    screen(
      p("Image 1"),
      tags$img(src = "https://placehold.it/900x500/3c8dbc/ffffff&text=This+is+slide+1")
    ),
    screen(
      p("Image 2"),
      tags$img(src = "https://placehold.it/900x500/39CCCC/ffffff&text=This+is+slide+2")
    )
  )
)

server <- function(input, output, session) {
}

shinyApp(ui, server)
```

**Comment by juba** [comment]
Hi,

There is no implementation of Glide.js [bullets](https://glidejs.com/docs/setup/#bullets) in `shinyglide`. The only way to add an indicator would be to add bullets tags in a [custom controls](https://github.com/juba/shinyglide/blob/master/inst/examples/04_custom_controls/app.R) implementation, and add the CSS to style them. Something like : 

```r
controls <- tagList(
    glideControls(),
    tags$div(class="glide__bullets", `data-glide-el`="controls[nav]",
      tags$span(class="glide__bullet"),
      tags$span(class="glide__bullet"),
      tags$span(class="glide__bullet"),
      tags$span(class="glide__bullet")
    )
  )
```

With a CSS like : 

```css
.glide__bullets {
  position: absolute;
  bottom: 10px;
  left: 100px;
}

.glide__bullet {
  width: 1em;
  height: 1em;
  background-color: #CCC;
  display: inline-block;
}

.glide__bullet--active {
  background-color: #444;
}
```

But there would be limitations, such as I don't think you could have the number of slides determined automatically.
